language: ruby
dist: trusty
install:
  - gem uninstall bundler
  - gem install bundler --version '1.14.6'
rvm:
  - rbx-3.74
script: bundle exec rspec
services: postgresql
before_script: 
 - "psql -c 'create database piecemaker2_test;' -U postgres"
 - "cp config/config.sample.yml config/config.yml"
 - "sed -i 's/username  : XXX/username  : postgres/g' config/config.yml" 
 - "sed -i 's/password  : XXX/password  : /g' config/config.yml" 
 - "cat config/config.yml" 
 - "bundle exec rake db:migrate[test]"