production:
  adapter: postgresql
  encoding: utf-8
  database: piecemaker2_prod
  pool: 5
  username: mattes
  password: 

development:
  adapter: postgresql
  encoding: utf-8
  database: piecemaker2_dev
  pool: 5
  username: mattes
  password: 

test:
  adapter: postgresql
  encoding: utf-8
  database: piecemaker2_test
  pool: 5
  username: mattes
  password: 