development:
  sessions:
    default:
      database: piecemaker
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: piecemaker
      hosts:
        - localhost:27017