# go to https://newrelic.com, sign up and get your license key
# license key is only needed, when newrelic_monitor is true
enable_newrelic: false
newrelic_license_key:

production:
  adapter   : postgres
  host      : localhost
  port      : 5432
  database  : piecemaker2_prod
  username  : XXX
  password  : XXX
  max_connections: 4
  newrelic_monitor: false
  newrelic_developer: false

development:
  adapter   : postgres
  host      : localhost
  port      : 5432
  database  : piecemaker2_dev
  username  : XXX
  password  : XXX
  max_connections: 4
  newrelic_monitor: false
  newrelic_developer: true

test:
  adapter   : postgres
  host      : localhost
  port      : 5432
  database  : piecemaker2_test
  username  : XXX
  password  : XXX
  max_connections: 4
  newrelic_monitor: false
  newrelic_developer: false