# go to https://newrelic.com, sign up and get your license key
newrelic_license_key: XXXX

production:
  adapter   : postgres
  host      : localhost
  database  : pm2_youtube_annotate_prod
  username  : yta
  password  : yta
  max_connections: 4

development:
  adapter   : postgres
  host      : localhost
  database  : pm2_youtube_annotate_dev
  username  : yta
  password  : yta
  max_connections: 4

test:
  adapter   : postgres
  host      : localhost
  database  : pm2_youtube_annotate_test
  username  : postgres
  password  : postgres
  max_connections: 4